CONFIG_BT_POWER_PROFILING_NFC_DISABLED=y
CONFIG_BT_POWER_PROFILING_LED_DISABLED=y
CONFIG_NFC_T2T_NRFXLIB=n
CONFIG_BT_POWER_PROFILING_CONNECTABLE_ADV_DURATION=300
CONFIG_BT_POWER_PROFILING_NON_CONNECTABLE_ADV_DURATION=300
CONFIG_BT_POWER_PROFILING_NOTIFICATION_TIMEOUT=3000
