# SPDX-License-Identifier: MIT

CONFIG_NUCODE_BLE_MESH_UPDATE=y

CONFIG_BT_SMP=y
CONFIG_BT_BONDABLE=y
CONFIG_BT_SMP_SC_PAIR_ONLY=y

CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_IMG_ENABLE_IMAGE_CHECK=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_REBOOT=y

CONFIG_BT_MESH_MODEL_EXTENSIONS=y
CONFIG_BT_MESH_MODEL_EXTENSION_LIST_SIZE=4
CONFIG_BT_MESH_BLOB_SRV=y
CONFIG_BT_MESH_BLOB_CLI=y
CONFIG_BT_MESH_BLOB_IO_FLASH=y
CONFIG_BT_MESH_BLOB_SIZE_MAX=720896
CONFIG_BT_MESH_BLOB_BLOCK_SIZE_MIN=4096
CONFIG_BT_MESH_BLOB_BLOCK_SIZE_MAX=4096
CONFIG_BT_MESH_BLOB_CHUNK_COUNT_MAX=32
CONFIG_BT_MESH_ALIGN_CHUNK_SIZE_TO_MAX_SEGMENT=n
CONFIG_BT_MESH_RX_BLOB_CHUNK_SIZE=128
CONFIG_BT_MESH_TX_BLOB_CHUNK_SIZE=128
CONFIG_BT_MESH_BLOB_CLI_BLOCK_RETRIES=3
CONFIG_BT_MESH_DFU_SRV=y
CONFIG_BT_MESH_DFU_CLI=y
CONFIG_BT_MESH_DFU_METADATA=y
CONFIG_BT_MESH_DFU_FWID_MAXLEN=16
CONFIG_BT_MESH_DFU_METADATA_MAXLEN=32
CONFIG_BT_MESH_DFU_SLOTS=y
CONFIG_BT_MESH_DFU_SLOT_CNT=1
CONFIG_BT_MESH_DFD_SRV=y
CONFIG_BT_MESH_DFD_SRV_SLOT_MAX_SIZE=720896
CONFIG_BT_MESH_DFD_SRV_SLOT_SPACE=720896
CONFIG_BT_MESH_DFD_SRV_TARGETS_MAX=4

CONFIG_BT_MESH_SAR_TX_UNICAST_RETRANS_COUNT=5
CONFIG_BT_MESH_SAR_TX_UNICAST_RETRANS_WITHOUT_PROG_COUNT=3
CONFIG_BT_MESH_SAR_RX_ACK_RETRANS_COUNT=0x0
CONFIG_BT_MESH_SAR_RX_ACK_DELAY_INC=0x7
CONFIG_BT_MESH_SAR_RX_SEG_INT_STEP=0xf
CONFIG_BT_MESH_SAR_RX_SEG_THRESHOLD=0x1f
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_BT_RX_STACK_SIZE=5120
