/**
 * @file nu54dk-arduino-pin-metadata.h
 * @brief NU54DK Arduino pin map에서 공유하는 고정 metadata 값입니다.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef NUCODE_DTS_NU54DK_ARDUINO_PIN_METADATA_H_
#define NUCODE_DTS_NU54DK_ARDUINO_PIN_METADATA_H_

#define NUCODE_PIN_CAP_INPUT (1 << 0)
#define NUCODE_PIN_CAP_OUTPUT (1 << 1)
#define NUCODE_PIN_CAP_INTERRUPT (1 << 2)
#define NUCODE_PIN_CAP_OPEN_DRAIN (1 << 3)
#define NUCODE_PIN_CAP_ANALOG (1 << 4)
#define NUCODE_PIN_CAP_PWM (1 << 5)
#define NUCODE_PIN_CAP_WAKEUP (1 << 6)

#define NUCODE_PIN_POLICY_NORMAL 0
#define NUCODE_PIN_POLICY_INPUT_ONLY 1
#define NUCODE_PIN_POLICY_TRANSFERABLE 2
#define NUCODE_PIN_POLICY_CONDITIONAL_LFXO 3
#define NUCODE_PIN_POLICY_CONDITIONAL_DAP_UART 4
#define NUCODE_PIN_POLICY_SYSTEM_RESERVED 5

#define NUCODE_PIN_OWNER_BOARD_LED 0
#define NUCODE_PIN_OWNER_BOARD_BUTTON 1
#define NUCODE_PIN_OWNER_CONNECTOR_GPIO 2
#define NUCODE_PIN_OWNER_WIRE 3
#define NUCODE_PIN_OWNER_SPI 4
#define NUCODE_PIN_OWNER_PWM 5
#define NUCODE_PIN_OWNER_ADC 6
#define NUCODE_PIN_OWNER_SERIAL 7
#define NUCODE_PIN_OWNER_SYSTEM 8
#define NUCODE_PIN_OWNER_CONDITIONAL 9

#define NUCODE_PIN_ROUTE_GPIO (1 << 0)
#define NUCODE_PIN_ROUTE_GPIOTE (1 << 1)
#define NUCODE_PIN_ROUTE_ADC (1 << 2)
#define NUCODE_PIN_ROUTE_LFXO (1 << 3)
#define NUCODE_PIN_ROUTE_NFCT (1 << 4)
#define NUCODE_PIN_ROUTE_UART20_CONSOLE (1 << 5)
#define NUCODE_PIN_ROUTE_UART30 (1 << 6)
#define NUCODE_PIN_ROUTE_I2C22 (1 << 7)
#define NUCODE_PIN_ROUTE_SPI00 (1 << 8)
#define NUCODE_PIN_ROUTE_PWM20 (1 << 9)
#define NUCODE_PIN_ROUTE_PMIC (1 << 10)
#define NUCODE_PIN_ROUTE_BOARD_LED (1 << 11)
#define NUCODE_PIN_ROUTE_BOARD_BUTTON (1 << 12)
#define NUCODE_PIN_ROUTE_HEADER (1 << 13)
#define NUCODE_PIN_ROUTE_PORT0 (1 << 14)
#define NUCODE_PIN_ROUTE_PORT1 (1 << 15)
#define NUCODE_PIN_ROUTE_PORT2 (1 << 16)
#define NUCODE_PIN_ROUTE_PWM21 (1 << 17)
#define NUCODE_PIN_ROUTE_PWM22 (1 << 18)

#endif
