set(NUCODE_BUILD_RECORD_SCRIPT
  "${CMAKE_CURRENT_LIST_DIR}/write_build_record.cmake"
)

add_custom_target(nucode_arduino_core_build_record ALL
  COMMAND "${CMAKE_COMMAND}"
    "-DNUCODE_CORE_ROOT=${NUCODE_ARDUINO_CORE_ROOT}"
    "-DNUCODE_APPLICATION_SOURCE_DIR=${APPLICATION_SOURCE_DIR}"
    "-DNUCODE_BOARD_PACKAGE_ROOT=${NUCODE_BOARD_PACKAGE_ROOT}"
    "-DNUCODE_NRF_DIR=${NRF_DIR}"
    "-DNUCODE_ZEPHYR_BASE=${ZEPHYR_BASE}"
    "-DNUCODE_GIT_EXECUTABLE=${GIT_EXECUTABLE}"
    "-DNUCODE_BUILD_RECORD=${NUCODE_BUILD_RECORD}"
    "-DNUCODE_BOARD=${BOARD}"
    "-DNUCODE_BOARD_QUALIFIERS=${BOARD_QUALIFIERS}"
    "-DNUCODE_TOOLCHAIN_VARIANT=${ZEPHYR_TOOLCHAIN_VARIANT}"
    "-DNUCODE_TOOLCHAIN_PATH=${ZEPHYR_SDK_INSTALL_DIR}"
    "-DNUCODE_CXX_COMPILER=${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}"
    -P "${NUCODE_BUILD_RECORD_SCRIPT}"
  BYPRODUCTS "${NUCODE_BUILD_RECORD}"
  VERBATIM
)

message(STATUS
  "NUCODE Arduino Core ${NUCODE_CORE_REVISION}; "
  "NU54DK board ${NUCODE_BOARD_REVISION}"
)
