# @brief Core 소스 identity와 설치 배포 version을 각각 검증해 읽습니다.
function(nucode_product_identity root source_output package_output)
  set(header "${root}/cores/arduino/internal/CoreIdentity.h")
  set(platform "${root}/platform.txt")
  if(NOT EXISTS "${header}" OR NOT EXISTS "${platform}")
    message(FATAL_ERROR "[NU54:E_PRODUCT_IDENTITY] Core identity inputs are missing")
  endif()
  file(STRINGS "${header}" definitions REGEX "^#define[ \t]+NUCODE_CORE_SOURCE_VERSION[ \t]+")
  list(LENGTH definitions definition_count)
  file(STRINGS "${platform}" versions REGEX "^version=")
  list(LENGTH versions version_count)
  if(NOT definition_count EQUAL 1 OR NOT version_count EQUAL 1)
    message(FATAL_ERROR "[NU54:E_PRODUCT_IDENTITY] Expected one source and package version")
  endif()
  if(NOT "${definitions}" MATCHES "^#define[ \t]+NUCODE_CORE_SOURCE_VERSION[ \t]+\"([^\"]+)\"[ \t]*$")
    message(FATAL_ERROR "[NU54:E_PRODUCT_IDENTITY] Invalid source version definition")
  endif()
  set(source_version "${CMAKE_MATCH_1}")
  string(REGEX REPLACE "^version=" "" package_version "${versions}")
  set(version_pattern "^[0-9]+\\.[0-9]+\\.[0-9]+(-[0-9A-Za-z.-]+)?(\\+[0-9A-Za-z.-]+)?$")
  if(NOT "${source_version}" MATCHES "${version_pattern}" OR
     NOT "${package_version}" MATCHES "${version_pattern}")
    message(FATAL_ERROR "[NU54:E_PRODUCT_IDENTITY] Invalid product version")
  endif()
  set(${source_output} "${source_version}" PARENT_SCOPE)
  set(${package_output} "${package_version}" PARENT_SCOPE)
endfunction()
