# SPDX-License-Identifier: MIT
CONFIG_NUCODE_BLE_MESH_MANAGEMENT=y
CONFIG_NUCODE_BLE_MESH_MANAGEMENT_EVENT_QUEUE_SIZE=16
CONFIG_BT_MESH_MODEL_EXTENSIONS=y
CONFIG_BT_MESH_RPR_CLI=y
CONFIG_BT_MESH_RPR_SRV=y
CONFIG_BT_MESH_RPR_AD_TYPES_MAX=4
CONFIG_BT_MESH_RPR_SRV_SCANNED_ITEMS_MAX=4
CONFIG_BT_MESH_RPR_SRV_AD_DATA_MAX=31
CONFIG_BT_MESH_SAR_CFG_CLI=y
CONFIG_BT_MESH_SAR_CFG_SRV=y
CONFIG_BT_MESH_OP_AGG_CLI=y
CONFIG_BT_MESH_OP_AGG_SRV=y
CONFIG_BT_MESH_LARGE_COMP_DATA_CLI=y
CONFIG_BT_MESH_LARGE_COMP_DATA_SRV=y
CONFIG_BT_MESH_MODELS_METADATA_PAGE_LEN=150
CONFIG_BT_MESH_PRIV_BEACONS=y
CONFIG_BT_MESH_PRIV_BEACON_CLI=y
CONFIG_BT_MESH_PRIV_BEACON_SRV=y
CONFIG_BT_MESH_OD_PRIV_PROXY_CLI=y
CONFIG_BT_MESH_OD_PRIV_PROXY_SRV=y
CONFIG_BT_MESH_SOL_PDU_RPL_CLI=y
CONFIG_BT_MESH_PROXY_SOLICITATION=y
CONFIG_BT_MESH_PROXY_SRPL_SIZE=10
CONFIG_BT_MESH_BRG_CFG_CLI=y
CONFIG_BT_MESH_BRG_CFG_SRV=y
CONFIG_BT_MESH_BRG_TABLE_ITEMS_MAX=16
