# SPDX-License-Identifier: MIT
CONFIG_BT_MAX_CONN=1
CONFIG_BT_OTS=y
CONFIG_BT_GATT_AUTHORIZATION_CUSTOM=y
CONFIG_BT_OTS_MAX_OBJ_CNT=4
CONFIG_BT_OTS_OBJ_MAX_NAME_LEN=32
CONFIG_BT_OTS_OACP_CREATE_SUPPORT=y
CONFIG_BT_OTS_OACP_DELETE_SUPPORT=y
CONFIG_BT_OTS_OACP_WRITE_SUPPORT=y
CONFIG_BT_OTS_OACP_PATCH_SUPPORT=y
CONFIG_BT_OTS_OBJ_NAME_WRITE_SUPPORT=y
CONFIG_BT_OTS_OLCP_GO_TO_SUPPORT=y
