# SPDX-License-Identifier: MIT

CONFIG_NUCODE_ARDUINO_IO_RESOURCE_SLOTS=128

CONFIG_NUCODE_ARDUINO_SERIAL_FABRIC=y
CONFIG_NUCODE_ARDUINO_SERIAL_FABRIC_UARTE=y
CONFIG_NUCODE_ARDUINO_SERIAL_FABRIC_SPIM=y
CONFIG_NUCODE_ARDUINO_SERIAL_FABRIC_SPIS=y
CONFIG_NUCODE_ARDUINO_SERIAL_FABRIC_TWIM=y
CONFIG_NUCODE_ARDUINO_SERIAL_FABRIC_TWIS=y

CONFIG_NUCODE_ARDUINO_ANALOG_FABRIC=y
CONFIG_NUCODE_ARDUINO_EVENT_FABRIC=y
CONFIG_NUCODE_ARDUINO_STREAM_FABRIC=y
CONFIG_NUCODE_ARDUINO_SYSTEM_FABRIC=y

CONFIG_NRF_SYS_EVENT=y
CONFIG_NRF_SYS_EVENT_IRQ_LATENCY=n
