name=NUCODE BLE Companion
version=0.5.0
author=Quantum / NUCODE
maintainer=Quantum / NUCODE
sentence=NU54DK의 Apple ANCS와 AMS companion 기능을 제공합니다.
paragraph=보안 연결의 서비스 탐색, 알림과 미디어 정보, 사용자 명령 및 외부 ecosystem template를 제공합니다.
category=Communication
url=https://github.com/EIDOSDATA/NU54DK_Arduino_Core
architectures=zephyr
depends=NUCODE BLE
includes=NUCODE_BLE_Companion.h
