# SPDX-License-Identifier: MIT

CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=y
CONFIG_BOOT_VERSION_CMP_USE_BUILD_NUMBER=y
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION_SECURITY_COUNTER=y

CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_MINIMAL_LIBC=y
CONFIG_FPROTECT=y
CONFIG_MAIN_STACK_SIZE=8192
