# SPDX-License-Identifier: MIT
CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_NUCODE_ARDUINO_SERIAL1=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_CTLR_SDC_PERIPHERAL_COUNT=1
CONFIG_ESB_MPSL_TIMESLOT=y
CONFIG_MPSL_TIMESLOT_SESSION_COUNT=2
